<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-9702-1659068940/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
display= d['k1'][3]['tricky'][3]['target'][3]
display

'hello'

# Numpy

In [22]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [16]:
np.arange(20,35,2)


array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
x=np.arange(9)
x
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
a=np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [27]:
import pandas as pd


In [28]:
d={"Name":['abc','xyz','uvw'],"Age":[20,22,24]}
d1=pd.DataFrame(d)
d1          

Name  Age
0  abc   20
1  xyz   22
2  uvw   24

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [29]:
import datetime
start=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
end=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
x=pd.date_range(start,end)
x

DatetimeIndex(['2023-01-01'], dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [30]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:
l1=pd.DataFrame(lists)
l1

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24